import Image from "next/image";
import Head from "next/head";
import {useState} from "react";

function login() {
    // const [name, setName] = useState(0);
    // const [password, setPassword] = useState(0);
    function LoginRequest(){
        console.log(1)
    }
    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />

            </Head>
            <div className="container">
                <div className="flex min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
                    <form>
                        <input id="email-address" name="email" type="email" autoComplete="email" required
                               className="min-w-0 flex-auto rounded-md border-0 bg-white/5 px-3.5 py-2 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6"
                               placeholder="Enter your email" />
                        <input id="email-address" name="email" type="email" autoComplete="email" required
                               className="min-w-0 flex-auto rounded-md border-0 bg-white/5 px-3.5 py-2 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6"
                               placeholder="Enter your email" />
                        <button type='button' onClick={LoginRequest}>
                            login
                        </button>
                    </form>
                </div>
            </div>

        </>
);
}

export default login;