import Image from "next/image";
import Head from "next/head";
import {useState} from "react";

function login() {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const [name, setName] = useState(0);
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const [password, setPassword] = useState(0);
    function LoginRequest(){

        console.log(1)
    }
    // @ts-ignore
    // @ts-ignore
    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />

            </Head>
            <div className="container">
                <div className="flex min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
                    <form>
                        <input type="text"
                               name="mobile"
                               onChange={ e => setName(e.target.value)}
                               id="mobile"/>
                        <input type='text' name='password' id='password'/>
                        <button type='button' onClick={LoginRequest}>
                            login
                        </button>
                    </form>
                </div>
            </div>

        </>
);
}

export default login;